###
PUT http://localhost:8080/rockpaperscissors/player/player1
###
PUT http://localhost:8080/rockpaperscissors/player/player2
###
POST http://localhost:8080/rockpaperscissors/start HTTP/1.1
Content-Type: application/json

{
  "player": "player1"
}
###
POST http://localhost:8080/rockpaperscissors/join HTTP/1.1
Content-Type: application/json

{
  "gameId": "7538cc5d-1924-497f-8689-4805a15e54ef",
  "player": "player2"
}
###
POST http://localhost:8080/rockpaperscissors/play HTTP/1.1
Content-Type: application/json

{
  "gameId": "7538cc5d-1924-497f-8689-4805a15e54ef",
  "player": "player1",
  "move": "rock"
}
###
POST http://localhost:8080/rockpaperscissors/result HTTP/1.1
Content-Type: application/json

{
  "gameId": "7538cc5d-1924-497f-8689-4805a15e54ef",
  "player": "player1"
}
###
POST http://localhost:8080/rockpaperscissors/play HTTP/1.1
Content-Type: application/json

{
  "gameId": "7538cc5d-1924-497f-8689-4805a15e54ef",
  "player": "player2",
  "move": "scissors"
}
###
POST http://localhost:8080/rockpaperscissors/result HTTP/1.1
Content-Type: application/json

{
  "gameId": "7538cc5d-1924-497f-8689-4805a15e54ef",
  "player": "player2"
}
### returns winner