version: '3.3'

services:

  postgres:
    hostname: postgres.db
    image: postgres:11.2
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432

  rps-app-server:
    image: edekargaurav88/rps2:1.3
    container_name: app-server
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_URL=jdbc:postgresql://postgres.db:5432/postgres
      - SPRING_PROFILES_ACTIVE=prod,liquibase
    ports:
      - 8080:8080
      - 8091:8091