version: '3.3'

services:

  nginx-reverse-proxy:
    image: nginx:1.17
    container_name: nginx-reverse-proxy
    depends_on:
      - rps-app-server
    volumes:
      - './docker_resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 80:80

  rps-app-server:
    image: edekargaurav88/rps2:1.0
    container_name: app-server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_URL=jdbc:postgresql://192.168.10.195:5432/postgres
      - SPRING_PROFILES_ACTIVE=prod,liquibase
    ports:
      - 8080:8080